version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
