module.exports = function(grunt)
{
	grunt.registerTask(
		'build-dev',
		'Builds a combined library file without minification', [
			'jshint',
			'concat:development',
			'replace:development',
			'concat:worker',
			'replace:worker',
			'concat:displaynative',
			'replace:displaynative',
			'concat:displaycreatejs',
			'replace:displaycreatejs',
			'concat:displaypixi',
			'replace:displaypixi',
			'concat:game',
			'replace:game',
			'concat:tasks',
			'replace:tasks',
			'concat:states',
			'replace:states',
			'concat:sound',
			'replace:sound',
			'concat:captions',
			'replace:captions',
			'concat:interface',
			'replace:interface',
			'concat:translate',
			'replace:translate'
		]
	);
};